global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAS2F3ZIPTVL2RGRXA
        secret_key: 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
        port: 9100
