global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAS2F3ZIPTSBB2P2XB
        secret_key: 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
        port: 9100
