global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: ""
        secret_key: ""
        port: 9100

        




# global:
#   scrape_interval: 15s
#   external_labels:
#     monitor: 'prometheus'

# scrape_configs:
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['172.31.41.165:9090','172.31.47.62:9100','172.31.33.152:9100']
